version: '3.8'

services:

  keycloakdb:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    networks:
      - backend

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  keycloak_admin_ui:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak_admin_ui
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
    command: 
      - "start-dev"
      - --import-realm
    volumes:
      - ./keycloak/configuration/passkey-realm-and-client-export.json:/opt/keycloak/data/import/passkey-realm-and-client-export.json
#      - ./keycloak/themes/passkey/:/opt/keycloak/themes/passkey/
#      - ./auth/import:/opt/keycloak/data/import
    depends_on:
      - keycloakdb
    ports:
      - '9090:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: